# Google Cloud Build configuration for High Score Tracker
# This file defines the build and deployment process for Google Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/highscore-tracker:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/highscore-tracker:latest',
      '.'
    ]

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/highscore-tracker:$BUILD_ID']

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/highscore-tracker:latest']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'highscore-tracker',
      '--image', 'gcr.io/$PROJECT_ID/highscore-tracker:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars', 'REACT_APP_ENV=production,REACT_APP_VERSION=$BUILD_ID',
      '--set-env-vars', 'REACT_APP_GCP_PROJECT_ID=$PROJECT_ID',
      '--set-env-vars', 'REACT_APP_STORAGE_BUCKET=${_STORAGE_BUCKET}',
      '--service-account', '${_SERVICE_ACCOUNT}@$PROJECT_ID.iam.gserviceaccount.com'
    ]

# Build configuration
options:
  # Use higher CPU for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Enable logging
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build process
timeout: '1200s'

# Substitutions for customizable values
substitutions:
  # Default storage bucket name (can be overridden)
  _STORAGE_BUCKET: 'highscore-tracker-storage'
  # Service account for Cloud Run (can be overridden)
  _SERVICE_ACCOUNT: 'highscore-tracker-service'
  # Default region (can be overridden)
  _REGION: 'us-central1'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/highscore-tracker:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/highscore-tracker:latest'

# Build tags for organization
tags:
  - 'highscore-tracker'
  - 'react-app'
  - 'cloud-run'
